### ISSUE TITLE
Too Many Requests for url images.csv

### ISSUE THREAD

**Issue by v-lopez** [skypilot-org/skypilot#5438]
I have been trying to diagnose some scheduling in kubernetes and I had to start/stop jobs many times.
Then I hit this limit and was unable to launch jobs for 20minutes. There seems to be a 60req/hour limit https://docs.github.com/en/rest/using-the-rest-api/rate-limits-for-the-rest-api?apiVersion=2022-11-28

```
I 04-29 14:54:31 recovery_strategy.py:334]   Traceback: Traceback (most recent call last):
I 04-29 14:54:31 recovery_strategy.py:334]   File "/home/sky/skypilot-runtime/lib/python3.10/site-packages/sky/jobs/recovery_strategy.py", line 280, in _launch
I 04-29 14:54:31 recovery_strategy.py:334]     execution.launch(
I 04-29 14:54:31 recovery_strategy.py:334]   File "/home/sky/skypilot-runtime/lib/python3.10/site-packages/sky/utils/common_utils.py", line 465, in _record
I 04-29 14:54:31 recovery_strategy.py:334]     return f(*args, **kwargs)
I 04-29 14:54:31 recovery_strategy.py:334]   File "/home/sky/skypilot-runtime/lib/python3.10/site-packages/sky/utils/common_utils.py", line 465, in _record
I 04-29 14:54:31 recovery_strategy.py:334]     return f(*args, **kwargs)
I 04-29 14:54:31 recovery_strategy.py:334]   File "/home/sky/skypilot-runtime/lib/python3.10/site-packages/sky/execution.py", line 545, in launch
I 04-29 14:54:31 recovery_strategy.py:334]     return _execute(
I 04-29 14:54:31 recovery_strategy.py:334]   File "/home/sky/skypilot-runtime/lib/python3.10/site-packages/sky/execution.py", line 313, in _execute
I 04-29 14:54:31 recovery_strategy.py:334]     (handle, provisioning_skipped) = backend.provision(
I 04-29 14:54:31 recovery_strategy.py:334]   File "/home/sky/skypilot-runtime/lib/python3.10/site-packages/sky/utils/common_utils.py", line 465, in _record
I 04-29 14:54:31 recovery_strategy.py:334]     return f(*args, **kwargs)
I 04-29 14:54:31 recovery_strategy.py:334]   File "/home/sky/skypilot-runtime/lib/python3.10/site-packages/sky/utils/common_utils.py", line 445, in _record
I 04-29 14:54:31 recovery_strategy.py:334]     return f(*args, **kwargs)
I 04-29 14:54:31 recovery_strategy.py:334]   File "/home/sky/skypilot-runtime/lib/python3.10/site-packages/sky/backends/backend.py", line 86, in provision
I 04-29 14:54:31 recovery_strategy.py:334]     return self._provision(task, to_provision, dryrun, stream_logs,
I 04-29 14:54:31 recovery_strategy.py:334]   File "/home/sky/skypilot-runtime/lib/python3.10/site-packages/sky/backends/cloud_vm_ray_backend.py", line 2900, in _provision
I 04-29 14:54:31 recovery_strategy.py:334]     config_dict = retry_provisioner.provision_with_retries(
I 04-29 14:54:31 recovery_strategy.py:334]   File "/home/sky/skypilot-runtime/lib/python3.10/site-packages/sky/utils/common_utils.py", line 465, in _record
I 04-29 14:54:31 recovery_strategy.py:334]     return f(*args, **kwargs)
I 04-29 14:54:31 recovery_strategy.py:334]   File "/home/sky/skypilot-runtime/lib/python3.10/site-packages/sky/backends/cloud_vm_ray_backend.py", line 2055, in provision_with_retries
I 04-29 14:54:31 recovery_strategy.py:334]     config_dict = self._retry_zones(
I 04-29 14:54:31 recovery_strategy.py:334]   File "/home/sky/skypilot-runtime/lib/python3.10/site-packages/sky/backends/cloud_vm_ray_backend.py", line 1425, in _retry_zones
I 04-29 14:54:31 recovery_strategy.py:334]     config_dict = backend_utils.write_cluster_config(
I 04-29 14:54:31 recovery_strategy.py:334]   File "/home/sky/skypilot-runtime/lib/python3.10/site-packages/sky/utils/common_utils.py", line 465, in _record
I 04-29 14:54:31 recovery_strategy.py:334]     return f(*args, **kwargs)
I 04-29 14:54:31 recovery_strategy.py:334]   File "/home/sky/skypilot-runtime/lib/python3.10/site-packages/sky/backends/backend_utils.py", line 584, in write_cluster_config
I 04-29 14:54:31 recovery_strategy.py:334]     resources_vars = to_provision.make_deploy_variables(
I 04-29 14:54:31 recovery_strategy.py:334]   File "/home/sky/skypilot-runtime/lib/python3.10/site-packages/sky/resources.py", line 1098, in make_deploy_variables
I 04-29 14:54:31 recovery_strategy.py:334]     cloud_specific_variables = self.cloud.make_deploy_resources_variables(
I 04-29 14:54:31 recovery_strategy.py:334]   File "/home/sky/skypilot-runtime/lib/python3.10/site-packages/sky/clouds/kubernetes.py", line 449, in make_deploy_resources_variables
I 04-29 14:54:31 recovery_strategy.py:334]     ssh_jump_image = service_catalog.get_image_id_from_tag(
I 04-29 14:54:31 recovery_strategy.py:334]   File "/home/sky/skypilot-runtime/lib/python3.10/site-packages/sky/clouds/service_catalog/__init__.py", line 357, in get_image_id_from_tag
I 04-29 14:54:31 recovery_strategy.py:334]     return _map_clouds_catalog(clouds, 'get_image_id_from_tag', tag, region)
I 04-29 14:54:31 recovery_strategy.py:334]   File "/home/sky/skypilot-runtime/lib/python3.10/site-packages/sky/clouds/service_catalog/__init__.py", line 51, in _map_clouds_catalog
I 04-29 14:54:31 recovery_strategy.py:334]     results = subprocess_utils.run_in_parallel(_execute_catalog_method,
I 04-29 14:54:31 recovery_strategy.py:334]   File "/home/sky/skypilot-runtime/lib/python3.10/site-packages/sky/utils/subprocess_utils.py", line 131, in run_in_parallel
I 04-29 14:54:31 recovery_strategy.py:334]     return [func(args[0])]
I 04-29 14:54:31 recovery_strategy.py:334]   File "/home/sky/skypilot-runtime/lib/python3.10/site-packages/sky/clouds/service_catalog/__init__.py", line 49, in _execute_catalog_method
I 04-29 14:54:31 recovery_strategy.py:334]     return method(*args, **kwargs)
I 04-29 14:54:31 recovery_strategy.py:334]   File "/home/sky/skypilot-runtime/lib/python3.10/site-packages/sky/clouds/service_catalog/kubernetes_catalog.py", line 42, in get_image_id_from_tag
I 04-29 14:54:31 recovery_strategy.py:334]     image_id = common.get_image_id_from_tag_impl(_image_df, tag, region)
I 04-29 14:54:31 recovery_strategy.py:334]   File "/home/sky/skypilot-runtime/lib/python3.10/site-packages/sky/clouds/service_catalog/common.py", line 683, in get_image_id_from_tag_impl
I 04-29 14:54:31 recovery_strategy.py:334]     df = df[df['Tag'] == tag]
I 04-29 14:54:31 recovery_strategy.py:334]   File "/home/sky/skypilot-runtime/lib/python3.10/site-packages/sky/clouds/service_catalog/common.py", line 153, in __getitem__
I 04-29 14:54:31 recovery_strategy.py:334]     return self._load_df()[key]
I 04-29 14:54:31 recovery_strategy.py:334]   File "/home/sky/skypilot-runtime/lib/python3.10/site-packages/sky/clouds/service_catalog/common.py", line 145, in _load_df
I 04-29 14:54:31 recovery_strategy.py:334]     raise e
I 04-29 14:54:31 recovery_strategy.py:334]   File "/home/sky/skypilot-runtime/lib/python3.10/site-packages/sky/clouds/service_catalog/common.py", line 138, in _load_df
I 04-29 14:54:31 recovery_strategy.py:334]     self._update_func()
I 04-29 14:54:31 recovery_strategy.py:334]   File "/home/sky/skypilot-runtime/lib/python3.10/site-packages/sky/clouds/service_catalog/common.py", line 225, in _update_catalog
I 04-29 14:54:31 recovery_strategy.py:334]     raise e
I 04-29 14:54:31 recovery_strategy.py:334]   File "/home/sky/skypilot-runtime/lib/python3.10/site-packages/sky/clouds/service_catalog/common.py", line 211, in _update_catalog
I 04-29 14:54:31 recovery_strategy.py:334]     r.raise_for_status()
I 04-29 14:54:31 recovery_strategy.py:334]   File "/home/sky/skypilot-runtime/lib/python3.10/site-packages/requests/models.py", line 1024, in raise_for_status
I 04-29 14:54:31 recovery_strategy.py:334]     raise HTTPError(http_error_msg, response=self)
I 04-29 14:54:31 recovery_strategy.py:334] requests.exceptions.HTTPError: 429 Client Error: Too Many Requests for url: https://raw.githubusercontent.com/skypilot-org/skypilot-catalog/master/catalogs/v6/kubernetes/images.csv
I 04-29 14:54:31 recovery_strategy.py:334] 
```

**Comment by cg505** [comment]
We are also seeing this in CI - https://github.com/skypilot-org/skypilot/actions/runs/14738534522/job/41370597990?pr=5441

It's not clear that the API rate limits affect `raw.githubusercontent.com`. However, it does seem like something has changed. Maybe there is a global rate limit (not per-IP) that we are hitting due to heavy use.

**Comment by cg505** [comment]
https://github.com/orgs/community/discussions/157887

**Comment by Michaelvll** [comment]
This is happening more frequently, every CI seems experiencing this issue. We should fix this.

**Comment by zpoint** [comment]
https://github.com/orgs/community/discussions/157851#discussioncomment-12987612

https://github.blog/changelog/2025-05-08-updated-rate-limits-for-unauthenticated-requests/

Someone tested that even with a [GitHub token](https://github.com/orgs/community/discussions/157887#discussioncomment-13037133), the rate limit still exists.

**Comment by zpoint** [comment]
https://github.com/orgs/community/discussions/159645#discussioncomment-13187328
